CREATE INDEX "if_users_iduser_idx" ON "if" USING btree ("users_iduser");
ALTER TABLE "if" ADD FOREIGN KEY ("users_iduser") REFERENCES "users" ("iduser");
CREATE INDEX "if_modules_idmodule_idx" ON "if" USING btree ("modules_idmodule");
CREATE INDEX "if_permissions_idpermission_idx" ON "if" USING btree ("permissions_idpermission");
CREATE INDEX "if_roles_idrol_idx" ON "if" USING btree ("roles_idrol");
ALTER TABLE "if" ADD FOREIGN KEY ("modules_idmodule") REFERENCES "modules" ("idmodule");
ALTER TABLE "if" ADD FOREIGN KEY ("permissions_idpermission") REFERENCES "permissions" ("idpermission");
ALTER TABLE "if" ADD FOREIGN KEY ("roles_idrol") REFERENCES "roles" ("idrol");
CREATE INDEX "if_factors_idfactor_idx" ON "if" USING btree ("factors_idfactor");
CREATE INDEX "if_surveys_idsurvey_idx" ON "if" USING btree ("surveys_idsurvey");
ALTER TABLE "if" ADD FOREIGN KEY ("factors_idfactor") REFERENCES "factors" ("idfactor");
ALTER TABLE "if" ADD FOREIGN KEY ("surveys_idsurvey") REFERENCES "surveys" ("idsurvey");
CREATE INDEX "if_questions_idquestion_idx" ON "if" USING btree ("questions_idquestion");
ALTER TABLE "if" ADD FOREIGN KEY ("questions_idquestion") REFERENCES "questions" ("idquestion");
ALTER TABLE "if" ADD FOREIGN KEY ("factors_idfactor") REFERENCES "factors" ("idfactor");
CREATE INDEX "if_users_iduser_admin_idx" ON "if" USING btree ("users_iduser_admin");
CREATE INDEX "if_users_iduser_user_idx" ON "if" USING btree ("users_iduser_user");
ALTER TABLE "if" ADD FOREIGN KEY ("users_iduser_admin") REFERENCES "users" ("iduser");
ALTER TABLE "if" ADD FOREIGN KEY ("users_iduser_user") REFERENCES "users" ("iduser");
ALTER TABLE "if" ADD FOREIGN KEY ("roles_idrol") REFERENCES "roles" ("idrol");
ALTER TABLE "if" ADD FOREIGN KEY ("users_iduser") REFERENCES "users" ("iduser");
ALTER TABLE "if" ADD FOREIGN KEY ("surveys_idsurvey") REFERENCES "surveys" ("idsurvey");
ALTER TABLE "if" ADD FOREIGN KEY ("users_iduser") REFERENCES "users" ("iduser");
