-- MySQL Script generated by MySQL Workbench
-- Wed Feb  3 13:01:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sysurvey
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sysurvey` ;

-- -----------------------------------------------------
-- Schema Sysurvey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sysurvey` DEFAULT CHARACTER SET utf8 ;
USE `Sysurvey` ;

-- -----------------------------------------------------
-- Table `Sysurvey`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`users` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`factor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`factor` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`factor` (
  `idfactor` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `users_iduser` INT NOT NULL,
  PRIMARY KEY (`idfactor`),
  INDEX `fk_factor_users1_idx` (`users_iduser` ASC),
  CONSTRAINT `fk_factor_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `Sysurvey`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`rubric`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`rubric` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`rubric` (
  `idrubric` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `idfactor` INT NOT NULL,
  PRIMARY KEY (`idrubric`),
  INDEX `fk_rubric_factor1_idx` (`idfactor` ASC) ,
  CONSTRAINT `fk_rubric_factor1`
    FOREIGN KEY (`idfactor`)
    REFERENCES `Sysurvey`.`factor` (`idfactor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`module_permision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`module_permision` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`module_permision` (
  `idmodule_permision` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmodule_permision`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`module` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`module` (
  `idmodule` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `idmodule_type` INT NOT NULL,
  PRIMARY KEY (`idmodule`),
  INDEX `fk_module_module_type1_idx` (`idmodule_type` ASC),
  CONSTRAINT `fk_module_module_type1`
    FOREIGN KEY (`idmodule_type`)
    REFERENCES `Sysurvey`.`module_permision` (`idmodule_permision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`user_type` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`user_type` (
  `iduser_type` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `idmodule` INT NOT NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`iduser_type`),
  INDEX `fk_user_type_module1_idx` (`idmodule` ASC) ,
  INDEX `fk_user_type_users1_idx` (`iduser` ASC) ,
  CONSTRAINT `fk_user_type_module1`
    FOREIGN KEY (`idmodule`)
    REFERENCES `Sysurvey`.`module` (`idmodule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Sysurvey`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`survey` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`survey` (
  `idsurvey` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsurvey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`questions` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`questions` (
  `idquestion` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `idfactor` INT NOT NULL,
  `survey_idsurvey` INT NOT NULL,
  PRIMARY KEY (`idquestion`),
  INDEX `fk_questions_factor1_idx` (`idfactor` ASC) ,
  INDEX `fk_questions_survey1_idx` (`survey_idsurvey` ASC) ,
  CONSTRAINT `fk_questions_factor1`
    FOREIGN KEY (`idfactor`)
    REFERENCES `Sysurvey`.`factor` (`idfactor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_survey1`
    FOREIGN KEY (`survey_idsurvey`)
    REFERENCES `Sysurvey`.`survey` (`idsurvey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`support_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`support_languages` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`support_languages` (
  `idsupport_languages` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `iso639` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idsupport_languages`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`response` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`response` (
  `idresponse` INT NOT NULL AUTO_INCREMENT,
  `response` VARCHAR(45) NULL,
  `idquestion` INT NOT NULL,
  PRIMARY KEY (`idresponse`),
  INDEX `fk_response_questions1_idx` (`idquestion` ASC) ,
  CONSTRAINT `fk_response_questions1`
    FOREIGN KEY (`idquestion`)
    REFERENCES `Sysurvey`.`questions` (`idquestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`user_survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`user_survey` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`user_survey` (
  `iduser_survey` INT NOT NULL AUTO_INCREMENT,
  `users_iduser` INT NOT NULL,
  `survey_idsurvey` INT NOT NULL,
  `propietary` TINYINT NOT NULL,
  `complete` TINYINT NOT NULL,
  PRIMARY KEY (`iduser_survey`),
  INDEX `fk_user_survey_users1_idx` (`users_iduser` ASC) ,
  INDEX `fk_user_survey_survey1_idx` (`survey_idsurvey` ASC) ,
  CONSTRAINT `fk_user_survey_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `Sysurvey`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_survey_survey1`
    FOREIGN KEY (`survey_idsurvey`)
    REFERENCES `Sysurvey`.`survey` (`idsurvey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
