-- MySQL Script generated by MySQL Workbench
-- Wed Mar 24 17:03:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sysurvey
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sysurvey` ;

-- -----------------------------------------------------
-- Schema Sysurvey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sysurvey` DEFAULT CHARACTER SET utf8 ;
USE `Sysurvey` ;

-- -----------------------------------------------------
-- Table `Sysurvey`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`users` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `active` BINARY NOT NULL,
  `last_login` DATETIME NULL,
  `register_date` DATETIME NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`factors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`factors` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`factors` (
  `idfactor` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `users_iduser` INT NOT NULL,
  PRIMARY KEY (`idfactor`),
  INDEX `fk_factor_users1_idx` (`users_iduser` ASC),
  CONSTRAINT `fk_factor_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `Sysurvey`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`rubrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`rubrics` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`rubrics` (
  `idrubric` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `value` INT NOT NULL,
  `factors_idfactor` INT NOT NULL,
  PRIMARY KEY (`idrubric`),
  INDEX `fk_rubric_factor1_idx` (`factors_idfactor` ASC),
  CONSTRAINT `fk_rubric_factor1`
    FOREIGN KEY (`factors_idfactor`)
    REFERENCES `Sysurvey`.`factors` (`idfactor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`roles` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`roles` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`modules` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`modules` (
  `idmodule` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmodule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`permissions` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`permissions` (
  `idpermission` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpermission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`surveys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`surveys` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`surveys` (
  `idsurvey` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` BINARY NOT NULL,
  PRIMARY KEY (`idsurvey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`questions` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`questions` (
  `idquestion` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `mandatory` BINARY NOT NULL,
  `factors_idfactor` INT NOT NULL,
  `surveys_idsurvey` INT NOT NULL,
  PRIMARY KEY (`idquestion`),
  INDEX `fk_questions_factor1_idx` (`factors_idfactor` ASC),
  INDEX `fk_questions_survey1_idx` (`surveys_idsurvey` ASC),
  CONSTRAINT `fk_questions_factor1`
    FOREIGN KEY (`factors_idfactor`)
    REFERENCES `Sysurvey`.`factors` (`idfactor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_survey1`
    FOREIGN KEY (`surveys_idsurvey`)
    REFERENCES `Sysurvey`.`surveys` (`idsurvey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`responses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`responses` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`responses` (
  `idresponse` INT NOT NULL AUTO_INCREMENT,
  `response` INT NOT NULL,
  `questions_idquestion` INT NOT NULL,
  PRIMARY KEY (`idresponse`),
  INDEX `fk_response_questions1_idx` (`questions_idquestion` ASC),
  CONSTRAINT `fk_response_questions1`
    FOREIGN KEY (`questions_idquestion`)
    REFERENCES `Sysurvey`.`questions` (`idquestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`user_surveys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`user_surveys` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`user_surveys` (
  `iduser_survey` INT NOT NULL AUTO_INCREMENT,
  `users_iduser` INT NOT NULL,
  `surveys_idsurvey` INT NOT NULL,
  `propietary` BINARY NOT NULL,
  `complete` BINARY NOT NULL,
  `start_date` DATETIME NULL,
  `finish_date` DATETIME NULL,
  PRIMARY KEY (`iduser_survey`),
  INDEX `fk_user_survey_users1_idx` (`users_iduser` ASC),
  INDEX `fk_user_survey_survey1_idx` (`surveys_idsurvey` ASC),
  CONSTRAINT `fk_user_survey_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `Sysurvey`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_survey_survey1`
    FOREIGN KEY (`surveys_idsurvey`)
    REFERENCES `Sysurvey`.`surveys` (`idsurvey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`user_relations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`user_relations` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`user_relations` (
  `iduser_relations` INT NOT NULL AUTO_INCREMENT,
  `users_iduser_admin` INT NOT NULL,
  `users_iduser_user` INT NOT NULL,
  PRIMARY KEY (`iduser_relations`),
  INDEX `fk_user_relations_users1_idx` (`users_iduser_admin` ASC),
  INDEX `fk_user_relations_users2_idx` (`users_iduser_user` ASC),
  CONSTRAINT `fk_user_relations_users_admin`
    FOREIGN KEY (`users_iduser_admin`)
    REFERENCES `Sysurvey`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_relations_users_user`
    FOREIGN KEY (`users_iduser_user`)
    REFERENCES `Sysurvey`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`module_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`module_access` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`module_access` (
  `idmodule_access` INT NOT NULL AUTO_INCREMENT,
  `user_types_iduser_type` INT NOT NULL,
  `modules_idmodule` INT NOT NULL,
  `permissions_idpermission` INT NOT NULL,
  PRIMARY KEY (`idmodule_access`),
  INDEX `fk_module_access_user_types1_idx` (`user_types_iduser_type` ASC),
  INDEX `fk_module_access_modules1_idx` (`modules_idmodule` ASC),
  INDEX `fk_module_access_permissions1_idx` (`permissions_idpermission` ASC),
  CONSTRAINT `fk_module_access_user_types1`
    FOREIGN KEY (`user_types_iduser_type`)
    REFERENCES `Sysurvey`.`roles` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_module_access_modules1`
    FOREIGN KEY (`modules_idmodule`)
    REFERENCES `Sysurvey`.`modules` (`idmodule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_module_access_permissions1`
    FOREIGN KEY (`permissions_idpermission`)
    REFERENCES `Sysurvey`.`permissions` (`idpermission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`user_roles` (
  `iduser_rol` INT NOT NULL AUTO_INCREMENT,
  `users_iduser` INT NOT NULL,
  `roles_idrol` INT NOT NULL,
  PRIMARY KEY (`iduser_rol`),
  INDEX `fk_user_rol_users1_idx` (`users_iduser` ASC),
  INDEX `fk_user_rol_roles1_idx` (`roles_idrol` ASC),
  CONSTRAINT `fk_user_rol_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `Sysurvey`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_rol_roles1`
    FOREIGN KEY (`roles_idrol`)
    REFERENCES `Sysurvey`.`roles` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
