-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 20:54:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sysurvey
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sysurvey` ;

-- -----------------------------------------------------
-- Schema Sysurvey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sysurvey` DEFAULT CHARACTER SET utf8 ;
USE `Sysurvey` ;

-- -----------------------------------------------------
-- Table `Sysurvey`.`factor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`factor` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`factor` (
  `idfactor` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idfactor`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`rubric`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`rubric` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`rubric` (
  `idrubric` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `factor_idfactor` INT NOT NULL,
  PRIMARY KEY (`idrubric`),
  INDEX `fk_rubric_factor1_idx` (`factor_idfactor` ASC) )
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`module_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`module_type` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`module_type` (
  `idmodule_type` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmodule_type`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`module` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`module` (
  `idmodule` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `module_type_idmodule_type` INT NOT NULL,
  PRIMARY KEY (`idmodule`),
  INDEX `fk_module_module_type1_idx` (`module_type_idmodule_type` ASC) )
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`study_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`study_level` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`study_level` (
  `idstudy_level` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstudy_level`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`country` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`country` (
  `idcountry` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`sex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`sex` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`sex` (
  `idsex` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsex`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`data_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`data_user` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`data_user` (
  `iddata_user` INT NOT NULL AUTO_INCREMENT,
  `age` INT NOT NULL,
  `study_level_idstudy_level` INT NOT NULL,
  `country_idcountry` INT NOT NULL,
  `sex_idsex` INT NOT NULL,
  PRIMARY KEY (`iddata_user`),
  INDEX `fk_data_user_study_level1_idx` (`study_level_idstudy_level` ASC) ,
  INDEX `fk_data_user_country1_idx` (`country_idcountry` ASC) ,
  INDEX `fk_data_user_sex1_idx` (`sex_idsex` ASC) )
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`users` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `data_user_iddata_user` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_users_data_user1_idx` (`data_user_iddata_user` ASC) ,
  CONSTRAINT `fk_users_data_user1`
    FOREIGN KEY (`data_user_iddata_user`)
    REFERENCES `Sysurvey`.`data_user` (`iddata_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`user_type` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`user_type` (
  `iduser_type` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `module_idmodule` INT NOT NULL,
  `users_iduser` INT NOT NULL,
  PRIMARY KEY (`iduser_type`),
  INDEX `fk_user_type_module1_idx` (`module_idmodule` ASC) ,
  INDEX `fk_user_type_users1_idx` (`users_iduser` ASC) ,
  CONSTRAINT `fk_user_type_module1`
    FOREIGN KEY (`module_idmodule`)
    REFERENCES `Sysurvey`.`module` (`idmodule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `Sysurvey`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sysurvey`.`questionnaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`questionnaire` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`questionnaire` (
  `idquestionnaire` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `module_idmodule` INT NOT NULL,
  PRIMARY KEY (`idquestionnaire`),
  INDEX `fk_questionnaire_module1_idx` (`module_idmodule` ASC) )
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`questions` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`questions` (
  `idquestions` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `questionnaire_idquestionnaire` INT NOT NULL,
  `factor_idfactor` INT NOT NULL,
  PRIMARY KEY (`idquestions`),
  INDEX `fk_questions_questionnaire1_idx` (`questionnaire_idquestionnaire` ASC) ,
  INDEX `fk_questions_factor1_idx` (`factor_idfactor` ASC) )
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`support_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`support_languages` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`support_languages` (
  `idsupport_languages` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `iso639` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idsupport_languages`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Sysurvey`.`response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sysurvey`.`response` ;

CREATE TABLE IF NOT EXISTS `Sysurvey`.`response` (
  `idresponse` INT NOT NULL AUTO_INCREMENT,
  `response` VARCHAR(45) NULL,
  `questions_idquestions` INT NOT NULL,
  PRIMARY KEY (`idresponse`),
  INDEX `fk_response_questions1_idx` (`questions_idquestions` ASC) ,
  CONSTRAINT `fk_response_questions1`
    FOREIGN KEY (`questions_idquestions`)
    REFERENCES `Sysurvey`.`questions` (`idquestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
